spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageTopicToAccept: "order-status-topic"
    kafkaMessageTopicToSend: "order-topic"
    kafkaMessageGroupId: "kafka-message-group-id-1"